services:
  - mysql
before_script:
  - mysql -c 'create database coherence_test;' -U root
language: elixir
elixir:
  - 1.7
otp_release:
  - 22.0
matrix:
sudo: false
notification:
  recipients:
    - rexmundi.rafael@gmail.com
